import { Patient, Medication, MedicationOrder } from './types';

export const patients: Patient[] = [
  {
    id: '1',
    name: 'John Brown',
    room: '3',
    bedNumber: '301',
    allergies: ['Penicillin'],
    dateOfBirth: '1965-03-15',
    gender: 'male',
  },
  {
    id: '2',
    name: 'Jane Doe',
    room: '5',
    bedNumber: '502',
    allergies: [],
    dateOfBirth: '1978-08-22',
    gender: 'female',
  },
  {
    id: '3',
    name: 'Robert Williams',
    room: '7',
    bedNumber: '701',
    allergies: ['Sulfa', 'Aspirin'],
    dateOfBirth: '1952-11-30',
    gender: 'male',
  },
  {
    id: '4',
    name: 'Sarah Johnson',
    room: '2',
    bedNumber: '204',
    allergies: ['Codeine'],
    dateOfBirth: '1990-06-18',
    gender: 'female',
  },
  {
    id: '5',
    name: 'Michael Chen',
    room: '8',
    bedNumber: '803',
    allergies: [],
    dateOfBirth: '1985-01-25',
    gender: 'male',
  },
];

export const medications: Medication[] = [
  {
    id: '1',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    brandNames: ['Amoxil', 'Trimox'],
    commonDosages: ['250mg', '500mg', '875mg'],
    routes: ['PO (Oral)'],
    category: 'Antibiotic',
  },
  {
    id: '2',
    name: 'Insulin Lispro',
    genericName: 'Insulin Lispro',
    brandNames: ['Humalog'],
    commonDosages: ['5 units', '10 units', '15 units', '20 units'],
    routes: ['SC (Subcutaneous)', 'IV (Intravenous)'],
    category: 'Antidiabetic',
  },
  {
    id: '3',
    name: 'Metformin',
    genericName: 'Metformin',
    brandNames: ['Glucophage', 'Fortamet'],
    commonDosages: ['500mg', '850mg', '1000mg'],
    routes: ['PO (Oral)'],
    category: 'Antidiabetic',
  },
  {
    id: '4',
    name: 'Lisinopril',
    genericName: 'Lisinopril',
    brandNames: ['Prinivil', 'Zestril'],
    commonDosages: ['5mg', '10mg', '20mg', '40mg'],
    routes: ['PO (Oral)'],
    category: 'ACE Inhibitor',
  },
  {
    id: '5',
    name: 'Omeprazole',
    genericName: 'Omeprazole',
    brandNames: ['Prilosec', 'Losec'],
    commonDosages: ['20mg', '40mg'],
    routes: ['PO (Oral)', 'IV (Intravenous)'],
    category: 'Proton Pump Inhibitor',
  },
  {
    id: '6',
    name: 'Morphine Sulfate',
    genericName: 'Morphine',
    brandNames: ['MS Contin', 'Kadian'],
    commonDosages: ['2mg', '4mg', '10mg', '15mg'],
    routes: ['PO (Oral)', 'IV (Intravenous)', 'IM (Intramuscular)'],
    category: 'Opioid Analgesic',
  },
  {
    id: '7',
    name: 'Ceftriaxone',
    genericName: 'Ceftriaxone',
    brandNames: ['Rocephin'],
    commonDosages: ['1g', '2g'],
    routes: ['IV (Intravenous)', 'IM (Intramuscular)'],
    category: 'Antibiotic',
  },
  {
    id: '8',
    name: 'Diclofenac',
    genericName: 'Diclofenac',
    brandNames: ['Voltaren', 'Cataflam'],
    commonDosages: ['25mg', '50mg', '75mg'],
    routes: ['PO (Oral)', 'Topical'],
    category: 'NSAID',
  },
];

const now = new Date();

export const medicationOrders: MedicationOrder[] = [
  {
    id: '1',
    patientId: '1',
    patient: patients[0],
    medication: medications[0],
    dosage: '500mg',
    frequency: 'Three times daily',
    route: 'PO (Oral)',
    orderedBy: 'Dr. Smith',
    orderedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    status: 'verified',
    dueTime: new Date(now.getTime() + 30 * 60 * 1000),
  },
  {
    id: '2',
    patientId: '2',
    patient: patients[1],
    medication: medications[1],
    dosage: '10 units',
    frequency: 'Before meals',
    route: 'SC (Subcutaneous)',
    orderedBy: 'Dr. Johnson',
    orderedAt: new Date(now.getTime() - 1 * 60 * 60 * 1000),
    status: 'dispensed',
    dueTime: new Date(now.getTime() + 15 * 60 * 1000),
  },
  {
    id: '3',
    patientId: '3',
    patient: patients[2],
    medication: medications[3],
    dosage: '10mg',
    frequency: 'Once daily',
    route: 'PO (Oral)',
    orderedBy: 'Dr. Smith',
    orderedAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    status: 'administered',
    dueTime: new Date(now.getTime() - 1 * 60 * 60 * 1000),
  },
  {
    id: '4',
    patientId: '4',
    patient: patients[3],
    medication: medications[4],
    dosage: '40mg',
    frequency: 'Once daily',
    route: 'PO (Oral)',
    orderedBy: 'Dr. Williams',
    orderedAt: new Date(now.getTime() - 30 * 60 * 1000),
    status: 'pending',
    dueTime: new Date(now.getTime() + 2 * 60 * 60 * 1000),
  },
  {
    id: '5',
    patientId: '5',
    patient: patients[4],
    medication: medications[2],
    dosage: '500mg',
    frequency: 'Twice daily',
    route: 'PO (Oral)',
    orderedBy: 'Dr. Johnson',
    orderedAt: new Date(now.getTime() - 3 * 60 * 60 * 1000),
    status: 'verified',
    dueTime: new Date(now.getTime() + 45 * 60 * 1000),
  },
];
